//! Stages every file the linker needs for every target and embeds it in the
//! compiler, so compiling for a target needs no toolchain installed.
//!
//! Sources are located the same way the runtime build locates them: the Rust
//! toolchain's own musl libc, a cross compiler's sysroot, or the macOS SDK. A
//! target missing any required piece is skipped with a warning; the compiler
//! then falls back to discovery for it.

use std::path::{Path, PathBuf};
use std::process::Command;

/// One file to stage: where it lands, and the names it may be found under.
struct Want {
    /// Path inside the staged sysroot.
    dest: String,
    /// Accept the first of these that exists.
    names: Vec<String>,
    required: bool,
}

fn want(dest: &str, required: bool) -> Want {
    let name = Path::new(dest).file_name().unwrap().to_string_lossy().into_owned();
    Want { dest: dest.to_string(), names: vec![name], required }
}

struct Spec {
    dir: String,
    os: &'static str,
    arch: String,
    libc: &'static str,
}

fn main() {
    println!("cargo:rerun-if-env-changed=PIPER_CROSS_TARGETS");
    println!("cargo:rerun-if-env-changed=PIPER_NO_BUNDLE");
    println!("cargo:rerun-if-env-changed=PIPER_SYSROOT");
    println!("cargo:rerun-if-env-changed=PIPER_SYSROOT_PATH");
    println!("cargo:rerun-if-env-changed=PIPER_STDLIB");
    println!("cargo:rerun-if-env-changed=PIPER_NO_STDLIB");
    for target in ["X86_64_LINUX_MUSL", "AARCH64_LINUX_MUSL", "X86_64_LINUX_GNU", "AARCH64_LINUX_GNU", "X86_64_WINDOWS_GNU", "AARCH64_WINDOWS_GNU", "X86_64_MACOS", "AARCH64_MACOS"] {
        println!("cargo:rerun-if-env-changed=PIPER_SYSROOT_{target}");
    }
    println!("cargo:rerun-if-changed=build.rs");

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let stage = out.join("bundle");
    let _ = std::fs::remove_dir_all(&stage);
    std::fs::create_dir_all(&stage).unwrap();

    let mut entries: Vec<(String, String)> = Vec::new();
    if std::env::var("PIPER_NO_BUNDLE").is_err() {
        let runtime_dir = std::env::var("DEP_PIPER_RT_RUNTIME_DIR").ok().map(PathBuf::from);
        for spec in specs() {
            match stage_target(&spec, &stage, runtime_dir.as_deref()) {
                Ok(files) => {
                    println!("cargo:warning=piper: bundled {} link inputs for {}", files.len(), spec.dir);
                    for f in files { entries.push((spec.dir.clone(), f)); }
                }
                Err(e) => println!("cargo:warning=piper: not bundling {}: {e}", spec.dir),
            }
        }
    }

    let mut src = String::from("// Generated by build.rs.\npub static ASSETS: &[Asset] = &[\n");
    for (target, rel) in &entries {
        src.push_str(&format!("    Asset {{ target: {target:?}, path: {rel:?}, bytes: include_bytes!(\"bundle/{target}/{rel}\") }},\n"));
    }
    src.push_str("];\n");
    std::fs::write(out.join("assets.rs"), src).unwrap();

    bundle_stdlib(&out);
}

/// Pack Python sources into one byte array plus a sorted lookup table. The
/// source installation path is used only while building and is never emitted.
fn bundle_stdlib(out: &Path) {
    let empty = || {
        std::fs::write(out.join("stdlib.bin"), []).unwrap();
        std::fs::write(out.join("stdlib.rs"), "static STDLIB: &[StdlibAsset] = &[];\n").unwrap();
    };
    if std::env::var("PIPER_NO_STDLIB").is_ok() {
        empty();
        return;
    }
    let root = match std::env::var("PIPER_STDLIB").ok().map(PathBuf::from).or_else(find_stdlib) {
        Some(path) => path,
        None => {
            println!("cargo:warning=piper: Python 3.14.7 standard library not found; only Piper compatibility modules will be bundled");
            empty();
            return;
        }
    };
    println!("cargo:rerun-if-changed={}", root.display());
    let mut files = Vec::new();
    collect_python_sources(&root, &root, &mut files);
    files.sort_by(|a, b| a.0.cmp(&b.0));
    files.dedup_by(|a, b| a.0 == b.0);

    let mut packed = Vec::new();
    let mut table = String::from("// Generated by build.rs.\nstatic STDLIB: &[StdlibAsset] = &[\n");
    let mut count = 0usize;
    for (name, path, package) in files {
        let mut bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("cannot read standard library source: {e}"));
        if std::str::from_utf8(&bytes).is_err() { continue; }
        adapt_source(&name, &mut bytes);
        let start = packed.len();
        packed.extend_from_slice(&bytes);
        table.push_str(&format!("    StdlibAsset {{ name: {name:?}, start: {start}, len: {}, package: {package} }},\n", bytes.len()));
        count += 1;
    }
    table.push_str("];\n");
    std::fs::write(out.join("stdlib.bin"), packed).unwrap();
    std::fs::write(out.join("stdlib.rs"), table).unwrap();
    println!("cargo:warning=piper: bundled {count} Python 3.14.7 standard library modules");
}

fn adapt_source(name: &str, bytes: &mut Vec<u8>) {
    if name != "collections" { return; }
    let source = std::str::from_utf8(bytes).unwrap();
    let original = "    code = f'lambda _cls, {arg_list}: _tuple_new(_cls, ({arg_list}))'\n    __new__ = eval(code, namespace)\n";
    let replacement = "    def __new__(_cls, *values):\n        if len(values) != num_fields:\n            raise TypeError(f'Expected {num_fields} arguments, got {len(values)}')\n        return tuple_new(_cls, values)\n";
    if source.contains(original) { *bytes = source.replace(original, replacement).into_bytes(); }
}

fn find_stdlib() -> Option<PathBuf> {
    for interpreter in ["python3.14", "python3"] {
        let Ok(output) = Command::new(interpreter).args(["-I", "-c", "import sys,sysconfig; assert sys.version_info[:3] == (3,14,7); print(sysconfig.get_path('stdlib'))"]).output() else { continue };
        if !output.status.success() { continue; }
        let path = PathBuf::from(String::from_utf8_lossy(&output.stdout).trim());
        if path.join("os.py").is_file() { return Some(path); }
    }
    None
}

fn collect_python_sources(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf, bool)>) {
    let Ok(read) = std::fs::read_dir(dir) else { return };
    let mut entries: Vec<_> = read.flatten().collect();
    entries.sort_by_key(|entry| entry.file_name());
    for entry in entries {
        let path = entry.path();
        let Ok(relative) = path.strip_prefix(root) else { continue };
        if relative.components().any(|part| matches!(part.as_os_str().to_str(), Some("site-packages" | "__pycache__"))) { continue; }
        if path.is_dir() {
            collect_python_sources(root, &path, out);
            continue;
        }
        if path.extension().and_then(|s| s.to_str()) != Some("py") { continue; }
        let mut parts: Vec<String> = relative.components().map(|part| part.as_os_str().to_string_lossy().into_owned()).collect();
        let Some(file) = parts.pop() else { continue };
        let stem = file.strip_suffix(".py").unwrap_or(&file);
        let package = stem == "__init__";
        if !package { parts.push(stem.to_string()); }
        if parts.is_empty() || parts.iter().any(|part| !valid_module_part(part)) { continue; }
        out.push((parts.join("."), path, package));
    }
}

fn valid_module_part(part: &str) -> bool {
    let mut chars = part.chars();
    chars.next().is_some_and(|c| c == '_' || c.is_alphabetic())
        && chars.all(|c| c == '_' || c.is_alphanumeric())
}

/// Targets to bundle for: the host plus the usual cross set, or an explicit list.
fn specs() -> Vec<Spec> {
    let host = std::env::var("TARGET").unwrap_or_default();
    let host_arch = if host.starts_with("aarch64") { "aarch64" } else { "x86_64" };
    let requested = std::env::var("PIPER_CROSS_TARGETS").unwrap_or_default();
    // An explicit list is taken literally, which is also how a build opts out
    // of bundling a platform whose files it may not redistribute.
    if !requested.trim().is_empty() {
        return requested.split(',').map(|s| s.trim()).filter(|s| !s.is_empty()).filter_map(parse_spec).collect();
    }
    let mut names: Vec<String> = {
        vec![
            "x86_64-linux-musl".into(), "aarch64-linux-musl".into(),
            "x86_64-linux-gnu".into(), "aarch64-linux-gnu".into(),
            "x86_64-windows-gnu".into(), "aarch64-windows-gnu".into(),
        ]
    };
    // The macOS SDK carries every architecture at once.
    if host.contains("apple") {
        for a in ["aarch64", "x86_64"] { names.push(format!("{a}-macos")); }
    } else {
        names.push(format!("{host_arch}-macos"));
    }
    names.iter().filter_map(|n| parse_spec(n)).collect()
}

fn parse_spec(name: &str) -> Option<Spec> {
    let n = name.to_ascii_lowercase();
    let arch = if n.starts_with("aarch64") || n.starts_with("arm64") { "aarch64" }
        else if n.starts_with("x86_64") || n.starts_with("amd64") { "x86_64" } else { return None };
    let (os, libc) = if n.contains("macos") || n.contains("apple") || n.contains("darwin") { ("macos", "") }
        else if n.contains("windows") || n.contains("mingw") { ("windows", if n.contains("msvc") { "-msvc" } else { "-gnu" }) }
        else if n.contains("linux") { ("linux", if n.contains("gnu") { "-gnu" } else { "-musl" }) }
        else { return None };
    // MSVC import libraries cannot be redistributed, so they are never bundled.
    if libc == "-msvc" { return None; }
    Some(Spec { dir: format!("{arch}-{os}{libc}"), os, arch: arch.to_string(), libc })
}

/// Copy every file `spec` needs into `stage/<dir>`, returning their relative paths.
fn stage_target(spec: &Spec, stage: &Path, runtime_dir: Option<&Path>) -> Result<Vec<String>, String> {
    let dest_root = stage.join(&spec.dir);
    let mut staged = Vec::new();
    match spec.os {
        "macos" => stage_macos(spec, &dest_root, &mut staged)?,
        "linux" => stage_linux(spec, &dest_root, &mut staged)?,
        _ => stage_windows(spec, &dest_root, &mut staged)?,
    }
    // Debug info for a libc nobody steps through only makes the compiler
    // bigger, and glibc compresses it in a way not every lld can read.
    for rel in &staged { strip_debug(&dest_root.join(rel)); }
    // The runtime archive travels with the sysroot it was compiled against.
    if let Some(rd) = runtime_dir {
        let a = rd.join(&spec.dir).join("libpiper_rt.a");
        if a.exists() { copy_into(&a, &dest_root, "lib/libpiper_rt.a", &mut staged)?; }
    }
    Ok(staged)
}

/// The SDK's linker stubs. They are text listing symbols, not code.
fn stage_macos(_spec: &Spec, dest: &Path, staged: &mut Vec<String>) -> Result<(), String> {
    let sdk = macos_sdk().ok_or("no macOS SDK found")?;
    let sys = sdk.join("usr/lib/libSystem.tbd");
    if !sys.exists() { return Err(format!("no libSystem.tbd in {}", sdk.display())); }
    // Both names, since the SDK reaches one through a symlink.
    for name in ["libSystem.tbd", "libSystem.B.tbd"] {
        copy_into(&sys, dest, &format!("usr/lib/{name}"), staged)?;
    }
    let sysdir = sdk.join("usr/lib/system");
    let rd = std::fs::read_dir(&sysdir).map_err(|e| format!("{}: {e}", sysdir.display()))?;
    let mut stubs: Vec<PathBuf> = rd.flatten().map(|e| e.path()).filter(|p| p.to_string_lossy().ends_with(".tbd")).collect();
    stubs.sort();
    for p in stubs {
        let name = p.file_name().unwrap().to_string_lossy().into_owned();
        copy_into(&p, dest, &format!("usr/lib/system/{name}"), staged)?;
    }
    Ok(())
}

fn stage_linux(spec: &Spec, dest: &Path, staged: &mut Vec<String>) -> Result<(), String> {
    let mut wants = if spec.libc == "-musl" {
        vec![want("lib/rcrt1.o", true), want("lib/crt1.o", false), want("lib/Scrt1.o", false),
             want("lib/crti.o", false), want("lib/crtn.o", false), want("lib/libc.a", true),
             // aarch64 musl calls compiler builtins for long double.
             want("lib/libgcc.a", false), want("lib/libgcc_eh.a", false)]
    } else {
        vec![want("lib/crt1.o", true), want("lib/Scrt1.o", false), want("lib/crti.o", true), want("lib/crtn.o", true),
             want("lib/libc.a", true), want("lib/libm.a", true), want("lib/libpthread.a", false),
             want("lib/librt.a", false), want("lib/libdl.a", false), want("lib/libc_nonshared.a", false),
             want("lib/libgcc.a", false), want("lib/libgcc_eh.a", false)]
    };
    // A libc built for static PIE is preferred; the Rust toolchain ships one for musl.
    let mut dirs = Vec::new();
    if spec.libc == "-musl" {
        if let Some(d) = rust_musl_dir(&spec.arch) { dirs.push(d); }
    }
    let sysroot = cross_sysroot(spec);
    if let Some(sr) = &sysroot {
        let multiarch = format!("usr/lib/{}-linux-gnu", spec.arch);
        for rel in ["lib", "usr/lib", "lib64", "usr/lib64", multiarch.as_str()] {
            let d = sr.join(rel);
            if d.exists() { dirs.push(d); }
        }
    }
    if let Some(d) = gcc_internal_dir(spec) { dirs.push(d); }
    if dirs.is_empty() { return Err("no libc found: install a cross toolchain or the matching Rust std".into()); }
    resolve(&mut wants, &dirs, dest, staged)
}

fn stage_windows(spec: &Spec, dest: &Path, staged: &mut Vec<String>) -> Result<(), String> {
    let mut wants = vec![
        want("lib/crt2.o", true), want("lib/dllcrt2.o", false), want("lib/crtbegin.o", true), want("lib/crtend.o", true),
        want("lib/libmingw32.a", true), want("lib/libmingwex.a", true), want("lib/libmsvcrt.a", true),
        want("lib/libkernel32.a", true), want("lib/libucrt.a", false), want("lib/libmoldname.a", false),
        want("lib/libadvapi32.a", false), want("lib/libshell32.a", false), want("lib/libuser32.a", false),
        want("lib/libgcc.a", true), want("lib/libgcc_eh.a", false),
    ];
    let mut dirs = Vec::new();
    if let Some(root) = mingw_root(spec) {
        for rel in ["lib", "usr/lib"] {
            let d = root.join(rel);
            if d.exists() { dirs.push(d); }
        }
    }
    if let Some(d) = gcc_internal_dir(spec) { dirs.push(d); }
    if dirs.is_empty() { return Err("no mingw toolchain found".into()); }
    resolve(&mut wants, &dirs, dest, staged)
}

/// Copy each want from the first directory that has it.
fn resolve(wants: &mut [Want], dirs: &[PathBuf], dest: &Path, staged: &mut Vec<String>) -> Result<(), String> {
    for w in wants {
        let found = dirs.iter().find_map(|d| w.names.iter().map(|n| d.join(n)).find(|p| p.is_file()));
        match found {
            Some(src) => { copy_into(&src, dest, &w.dest, staged)?; flatten_script(dest, &w.dest, dirs, staged)?; }
            None if w.required => return Err(format!("no {} in any of {}", w.dest, dirs.iter().map(|d| d.display().to_string()).collect::<Vec<_>>().join(", "))),
            None => {}
        }
    }
    Ok(())
}

/// glibc ships some libraries as linker scripts naming absolute paths. Stage
/// what they name and rewrite the script to plain names, so it resolves inside
/// the bundled sysroot instead of against the machine that built the compiler.
fn flatten_script(root: &Path, rel: &str, dirs: &[PathBuf], staged: &mut Vec<String>) -> Result<(), String> {
    let path = root.join(rel);
    let Ok(text) = std::fs::read_to_string(&path) else { return Ok(()) };
    if text.starts_with("!<arch>") || !text.contains('(') { return Ok(()); }
    let parent = Path::new(rel).parent().map(|p| p.to_string_lossy().into_owned()).unwrap_or_default();
    let mut rewritten = text.clone();
    for token in script_inputs(&text) {
        let name = Path::new(&token).file_name().map(|n| n.to_string_lossy().into_owned()).unwrap_or(token.clone());
        let dest_rel = if parent.is_empty() { name.clone() } else { format!("{parent}/{name}") };
        if !staged.contains(&dest_rel) {
            let src = std::path::Path::new(&token).to_path_buf();
            let found = if src.is_file() { Some(src) } else { dirs.iter().map(|d| d.join(&name)).find(|p| p.is_file()) };
            match found {
                Some(f) => { copy_into(&f, root, &dest_rel, staged)?; flatten_script(root, &dest_rel, dirs, staged)?; }
                // A script may name a library that is genuinely absent; the
                // linker reports that far more clearly than this build can.
                None => continue,
            }
        }
        rewritten = rewritten.replace(&token, &name);
    }
    if rewritten != text { std::fs::write(&path, rewritten).map_err(|e| e.to_string())?; }
    Ok(())
}

/// File names listed by a linker script's INPUT, GROUP or AS_NEEDED clauses.
fn script_inputs(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    for keyword in ["INPUT", "GROUP", "AS_NEEDED"] {
        let mut rest = text;
        while let Some(i) = rest.find(keyword) {
            rest = &rest[i + keyword.len()..];
            let Some(open) = rest.find('(') else { break };
            let Some(close) = rest[open..].find(')') else { break };
            for tok in rest[open + 1..open + close].split_whitespace() {
                let tok = tok.trim_matches(|c| c == '"' || c == ',');
                if tok.is_empty() || tok.starts_with('-') || tok.contains('(') { continue; }
                if !out.iter().any(|t: &String| t == tok) { out.push(tok.to_string()); }
            }
            rest = &rest[open + close..];
        }
    }
    out
}

/// Copy one file into the staged sysroot and record its relative path.
fn copy_into(src: &Path, root: &Path, rel: &str, staged: &mut Vec<String>) -> Result<(), String> {
    let dest = root.join(rel);
    std::fs::create_dir_all(dest.parent().unwrap()).map_err(|e| e.to_string())?;
    std::fs::copy(src, &dest).map_err(|e| format!("copying {}: {e}", src.display()))?;
    staged.push(rel.to_string());
    Ok(())
}

/// Drop debug sections from a staged object or archive. Best effort: a tool
/// that cannot rewrite the file leaves it as it was.
fn strip_debug(path: &Path) {
    let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
    if ext != "a" && ext != "o" { return; }
    let Some(tool) = objcopy_path() else { return };
    let _ = Command::new(tool).arg("--strip-debug").arg(path).output();
}

/// llvm-objcopy rewrites objects for any target; the Rust toolchain ships one.
fn objcopy_path() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("PIPER_OBJCOPY") { return Some(PathBuf::from(p)); }
    if let Ok(prefix) = std::env::var("PIPER_LLVM_PREFIX") {
        let p = PathBuf::from(prefix).join("bin/llvm-objcopy");
        if p.exists() { return Some(p); }
    }
    let out = Command::new("rustc").args(["--print", "sysroot"]).output().ok()?;
    if !out.status.success() { return None; }
    let root = PathBuf::from(String::from_utf8_lossy(&out.stdout).trim());
    for e in std::fs::read_dir(root.join("lib/rustlib")).ok()?.flatten() {
        let p = e.path().join("bin/llvm-objcopy");
        if p.exists() { return Some(p); }
    }
    None
}

fn rust_musl_dir(arch: &str) -> Option<PathBuf> {
    let out = Command::new("rustc").args(["--print", "sysroot"]).output().ok()?;
    if !out.status.success() { return None; }
    let root = PathBuf::from(String::from_utf8_lossy(&out.stdout).trim());
    let d = root.join(format!("lib/rustlib/{arch}-unknown-linux-musl/lib/self-contained"));
    if d.join("libc.a").exists() { Some(d) } else { None }
}

fn cross_sysroot(spec: &Spec) -> Option<PathBuf> {
    let var = format!("PIPER_SYSROOT_{}", spec.dir.to_uppercase().replace('-', "_"));
    if let Ok(v) = std::env::var(&var) { let p = PathBuf::from(v); if p.exists() { return Some(p); } }
    if let Some(p) = search_path_sysroot(spec) { return Some(p); }
    for name in cross_compilers(spec) {
        if let Some(p) = query_path(&name, "-print-sysroot") { return Some(p); }
    }
    None
}

/// mingw keeps headers and import libraries in `<prefix>/<triple>`, which the
/// driver does not report; find it from where it says crt2.o lives.
fn mingw_root(spec: &Spec) -> Option<PathBuf> {
    if let Some(p) = search_path_sysroot(spec) {
        // The import libraries sit under the target triple.
        for d in [p.join(format!("{}-w64-mingw32", spec.arch)), p.clone()] {
            if d.join("include/windows.h").exists() { return Some(d); }
        }
    }
    for name in cross_compilers(spec) {
        if let Some(p) = query_path(&name, "-print-file-name=crt2.o") {
            if let Some(root) = p.parent().and_then(|d| d.parent()) {
                if root.join("include/windows.h").exists() { return Some(root.to_path_buf()); }
            }
        }
    }
    None
}

/// The directory holding libgcc.a and the gcc-side CRT objects.
fn gcc_internal_dir(spec: &Spec) -> Option<PathBuf> {
    if let Some(root) = cross_sysroot(spec) {
        if let Some(d) = gcc_dirs(&root).into_iter().next_back() { return Some(d); }
    }
    for name in cross_compilers(spec) {
        if let Some(p) = query_path(&name, "-print-libgcc-file-name") { return p.parent().map(PathBuf::from); }
    }
    None
}

/// Versioned directories holding libgcc, under `lib/gcc` or `usr/lib/gcc`.
fn gcc_dirs(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    for rel in ["usr/lib/gcc", "lib/gcc"] {
        let Ok(triples) = std::fs::read_dir(root.join(rel)) else { continue };
        for t in triples.flatten() {
            let Ok(versions) = std::fs::read_dir(t.path()) else { continue };
            for v in versions.flatten() {
                if v.path().join("libgcc.a").exists() { out.push(v.path()); }
            }
        }
    }
    out.sort();
    out
}

/// Look for `spec`'s sysroot under `PIPER_SYSROOT_PATH`, a colon separated
/// list of directories holding sysroots named either the way piper names
/// targets or as `<libc>-<arch>` with the Debian spelling of the architecture.
fn search_path_sysroot(spec: &Spec) -> Option<PathBuf> {
    let raw = std::env::var("PIPER_SYSROOT_PATH").ok()?;
    let debian = if spec.arch == "aarch64" { "arm64" } else { "amd64" };
    let libc = match (spec.os, spec.libc) {
        ("linux", "-musl") => "musl",
        ("linux", _) => "glibc",
        ("windows", _) => "windows",
        _ => "macos",
    };
    let names = [spec.dir.clone(), format!("{libc}-{debian}"), format!("{libc}-{}", spec.arch)];
    for entry in raw.split(':').map(str::trim).filter(|s| !s.is_empty()) {
        for name in &names {
            let p = PathBuf::from(entry).join(name);
            if p.is_dir() { return Some(p); }
        }
    }
    None
}

fn cross_compilers(spec: &Spec) -> Vec<String> {
    let arch = &spec.arch;
    match (spec.os, spec.libc) {
        ("linux", "-musl") => vec![format!("{arch}-linux-musl-gcc"), format!("{arch}-unknown-linux-musl-gcc")],
        ("linux", _) => vec![format!("{arch}-linux-gnu-gcc"), format!("{arch}-unknown-linux-gnu-gcc")],
        ("windows", _) => vec![format!("{arch}-w64-mingw32-gcc"), format!("{arch}-w64-mingw32-clang")],
        _ => Vec::new(),
    }
}

fn query_path(compiler: &str, flag: &str) -> Option<PathBuf> {
    let out = Command::new(compiler).arg(flag).output().ok()?;
    if !out.status.success() { return None; }
    let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if s.is_empty() { return None; }
    PathBuf::from(s).canonicalize().ok()
}

fn macos_sdk() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("SDKROOT") { let p = PathBuf::from(p); if p.join("usr/lib/libSystem.tbd").exists() { return Some(p); } }
    let out = Command::new("xcrun").args(["--show-sdk-path"]).output().ok()?;
    if !out.status.success() { return None; }
    let p = PathBuf::from(String::from_utf8_lossy(&out.stdout).trim());
    if p.join("usr/lib/libSystem.tbd").exists() { Some(p) } else { None }
}
